# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monster.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='monster.proto',
  package='MyGame.Sample',
  syntax='proto3',
  serialized_pb=_b('\n\rmonster.proto\x12\rMyGame.Sample\"\xc3\x02\n\x07Monster\x12 \n\x03pos\x18\x01 \x01(\x0b\x32\x13.MyGame.Sample.Vec3\x12\x0c\n\x04mana\x18\x02 \x01(\x05\x12\n\n\x02hp\x18\x03 \x01(\x05\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x10\n\x08\x66riendly\x18\x05 \x01(\x08\x12\x11\n\tinventory\x18\x06 \x03(\x05\x12+\n\x05\x63olor\x18\x07 \x01(\x0e\x32\x1c.MyGame.Sample.Monster.Color\x12&\n\x07weapons\x18\x08 \x03(\x0b\x32\x15.MyGame.Sample.Weapon\x12*\n\x08\x65quipped\x18\t \x01(\x0b\x32\x18.MyGame.Sample.Equipment\x12!\n\x04path\x18\n \x03(\x0b\x32\x13.MyGame.Sample.Vec3\"%\n\x05\x43olor\x12\x07\n\x03Red\x10\x00\x12\t\n\x05Green\x10\x01\x12\x08\n\x04\x42lue\x10\x02\"\'\n\x04Vec3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"2\n\tEquipment\x12%\n\x06weapon\x18\x01 \x03(\x0b\x32\x15.MyGame.Sample.Weapon\"&\n\x06Weapon\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x61mage\x18\x02 \x01(\x05\"9\n\x0e\x41\x64\x64ressMonster\x12\'\n\x07monster\x18\x01 \x03(\x0b\x32\x16.MyGame.Sample.Monsterb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MONSTER_COLOR = _descriptor.EnumDescriptor(
  name='Color',
  full_name='MyGame.Sample.Monster.Color',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Red', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Green', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Blue', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=319,
  serialized_end=356,
)
_sym_db.RegisterEnumDescriptor(_MONSTER_COLOR)


_MONSTER = _descriptor.Descriptor(
  name='Monster',
  full_name='MyGame.Sample.Monster',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='MyGame.Sample.Monster.pos', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mana', full_name='MyGame.Sample.Monster.mana', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hp', full_name='MyGame.Sample.Monster.hp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='MyGame.Sample.Monster.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='friendly', full_name='MyGame.Sample.Monster.friendly', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inventory', full_name='MyGame.Sample.Monster.inventory', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='color', full_name='MyGame.Sample.Monster.color', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weapons', full_name='MyGame.Sample.Monster.weapons', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='equipped', full_name='MyGame.Sample.Monster.equipped', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='MyGame.Sample.Monster.path', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MONSTER_COLOR,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=356,
)


_VEC3 = _descriptor.Descriptor(
  name='Vec3',
  full_name='MyGame.Sample.Vec3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='MyGame.Sample.Vec3.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='MyGame.Sample.Vec3.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='MyGame.Sample.Vec3.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=397,
)


_EQUIPMENT = _descriptor.Descriptor(
  name='Equipment',
  full_name='MyGame.Sample.Equipment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weapon', full_name='MyGame.Sample.Equipment.weapon', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=449,
)


_WEAPON = _descriptor.Descriptor(
  name='Weapon',
  full_name='MyGame.Sample.Weapon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MyGame.Sample.Weapon.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='damage', full_name='MyGame.Sample.Weapon.damage', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=489,
)


_ADDRESSMONSTER = _descriptor.Descriptor(
  name='AddressMonster',
  full_name='MyGame.Sample.AddressMonster',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='monster', full_name='MyGame.Sample.AddressMonster.monster', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=548,
)

_MONSTER.fields_by_name['pos'].message_type = _VEC3
_MONSTER.fields_by_name['color'].enum_type = _MONSTER_COLOR
_MONSTER.fields_by_name['weapons'].message_type = _WEAPON
_MONSTER.fields_by_name['equipped'].message_type = _EQUIPMENT
_MONSTER.fields_by_name['path'].message_type = _VEC3
_MONSTER_COLOR.containing_type = _MONSTER
_EQUIPMENT.fields_by_name['weapon'].message_type = _WEAPON
_ADDRESSMONSTER.fields_by_name['monster'].message_type = _MONSTER
DESCRIPTOR.message_types_by_name['Monster'] = _MONSTER
DESCRIPTOR.message_types_by_name['Vec3'] = _VEC3
DESCRIPTOR.message_types_by_name['Equipment'] = _EQUIPMENT
DESCRIPTOR.message_types_by_name['Weapon'] = _WEAPON
DESCRIPTOR.message_types_by_name['AddressMonster'] = _ADDRESSMONSTER

Monster = _reflection.GeneratedProtocolMessageType('Monster', (_message.Message,), dict(
  DESCRIPTOR = _MONSTER,
  __module__ = 'monster_pb2'
  # @@protoc_insertion_point(class_scope:MyGame.Sample.Monster)
  ))
_sym_db.RegisterMessage(Monster)

Vec3 = _reflection.GeneratedProtocolMessageType('Vec3', (_message.Message,), dict(
  DESCRIPTOR = _VEC3,
  __module__ = 'monster_pb2'
  # @@protoc_insertion_point(class_scope:MyGame.Sample.Vec3)
  ))
_sym_db.RegisterMessage(Vec3)

Equipment = _reflection.GeneratedProtocolMessageType('Equipment', (_message.Message,), dict(
  DESCRIPTOR = _EQUIPMENT,
  __module__ = 'monster_pb2'
  # @@protoc_insertion_point(class_scope:MyGame.Sample.Equipment)
  ))
_sym_db.RegisterMessage(Equipment)

Weapon = _reflection.GeneratedProtocolMessageType('Weapon', (_message.Message,), dict(
  DESCRIPTOR = _WEAPON,
  __module__ = 'monster_pb2'
  # @@protoc_insertion_point(class_scope:MyGame.Sample.Weapon)
  ))
_sym_db.RegisterMessage(Weapon)

AddressMonster = _reflection.GeneratedProtocolMessageType('AddressMonster', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESSMONSTER,
  __module__ = 'monster_pb2'
  # @@protoc_insertion_point(class_scope:MyGame.Sample.AddressMonster)
  ))
_sym_db.RegisterMessage(AddressMonster)


# @@protoc_insertion_point(module_scope)
